### ISSUE TITLE
Metadata not updating in Emby

### ISSUE THREAD

**Issue by smokestacker** [ThePornDatabase/ThePornDB.bundle#53]
Hi, recently the plug in stopped updating the metadata in latest version of Emby. The plugin is matching the scene, but not pulling any data/actors but is just linking the scene to tpdb page. I am using latest dev build.

Error ThePornDB: Update error: "System.ArgumentNullException: Value cannot be null. (Parameter 'value')
   at Newtonsoft.Json.Linq.JToken.EnsureValue(JToken value)
   at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
   at ThePornDB.Providers.MetadataAPI.SceneUpdate(String sceneID, String url, CancellationToken cancellationToken)
   at ThePornDB.Providers.Base.GetMetadata(MovieInfo info, SceneType sceneType, CancellationToken cancellationToken)"

**Comment by DirtyRacer1337** [comment]
Wrong repo, anyway try update again, that error should appear only on previous build, https://github.com/ThePornDatabase/Jellyfin.Plugin.ThePornDB/releases/tag/latest
